### ISSUE TITLE
关于搜索到广告的过滤

### ISSUE THREAD

**Issue by lixiangpengcs** [xumengzi/Anti-Hundred-Poison#1]
感谢作者所做出来的贡献，我在使用的过程中发现对于搜索到的广告并没有做到过滤（非右侧广告），但是这些广告其实对于我们来说也没啥帮助，能否删除掉这些继续增加搜索的效率
![QQ截图20210128100708](https://user-images.githubusercontent.com/26785322/106079668-9fba5980-6150-11eb-90ed-723e01c326d7.png)

**Comment by xumengzi** [comment]
可以安排, 但是你能不能提供一下搜索结果.
目前我没法复现呢, 并没有看到你的截图里面的广告二字
![image](https://user-images.githubusercontent.com/15715076/106388427-68320280-6419-11eb-9933-ea5ad90ec00e.png)

**Comment by lixiangpengcs** [comment]
那很奇怪哦，我这边是按照说明安装了的（重新安装了一遍仍然出现同样的问题），并且能够过滤到一些无用的一些信息，难道关闭这样的广告还有特殊的按钮之类的吗？我看了拓展的开关是打开的
![广告](https://user-images.githubusercontent.com/26785322/106412435-bcbd9800-6482-11eb-9abb-4a4588244373.png)

**Comment by xumengzi** [comment]
可能是你的筛选条件和我不一样
另外我也装了Adblock Plus插件的，两者一起复用效果更佳

**Comment by xumengzi** [comment]
你在试试呢，我最近又更新插件，你重新下载安装一下

**Comment by lixiangpengcs** [comment]
@xumengzi 多谢多谢，我再尝试一下给您反馈
