### ISSUE TITLE
广告也没屏蔽啊

### ISSUE THREAD

**Issue by ricardo-mf-lee** [xumengzi/Anti-Hundred-Poison#2]
![image](https://user-images.githubusercontent.com/81803581/113400954-35829700-93d5-11eb-9e44-eb0238a0ea94.png)

**Comment by xumengzi** [comment]
你是怎么搜出来的，我和你的界面咋不一样
能不能把你的情况具体描述一下

**Comment by xumengzi** [comment]
你现在在看看呢，重新安装一下屏蔽插件，我更新了一下

**Comment by ricardo-mf-lee** [comment]
> 你是怎么搜出来的，我和你的界面咋不一样
> 能不能把你的情况具体描述一下

装了插件访问百度搜索就是这个界面啊

**Comment by xumengzi** [comment]
> > 你是怎么搜出来的，我和你的界面咋不一样
> > 能不能把你的情况具体描述一下
> 
> 装了插件访问百度搜索就是这个界面啊

我更新了一下，再去重新安装试试，另外也可以安装一下adblock插件，一起使用

**Comment by xumengzi** [comment]
> > > 你是怎么搜出来的，我和你的界面咋不一样
> > > 能不能把你的情况具体描述一下
> > 
> > 
> > 装了插件访问百度搜索就是这个界面啊
> 
> 我更新了一下，再去重新安装试试，另外也可以安装一下adblock插件，一起使用
