### ISSUE TITLE
可以做成油猴脚本吗？

### ISSUE THREAD

**Issue by lifei6671** [xumengzi/Anti-Hundred-Poison#3]
感觉做成油猴脚本就不用加载扩展了。

**Comment by xumengzi** [comment]
> 感觉做成油猴脚本就不用加载扩展了。

可以的, 是个好想法!
我去试试

**Comment by xumengzi** [comment]
> 感觉做成油猴脚本就不用加载扩展了。

已经弄好了，欢迎尝试  可以点： https://greasyfork.org/zh-CN/scripts/455226-anti-hundred-poison-%E5%B1%8F%E8%94%BD%E7%99%BE%E5%BA%A6%E7%9B%B8%E5%85%B3%E7%9A%84%E8%84%9A%E6%9C%AC

也可以再https://greasyfork.org/zh-CN  里搜索：Anti-Hundred-Poison
