### ISSUE TITLE
非常nice，期望关键词可自行扩展

### ISSUE THREAD

**Issue by Lingyj** [xumengzi/Anti-Hundred-Poison#6]

**Comment by xumengzi** [comment]
来试试：[油猴插件](https://greasyfork.org/zh-CN/scripts/455226-anti-hundred-poison-%E5%B1%8F%E8%94%BD%E7%99%BE%E5%BA%A6%E7%9B%B8%E5%85%B3%E7%9A%84%E8%84%9A%E6%9C%AC)

效果更好，想屏蔽啥就屏蔽啥
